services:
  app-tests:
    build: .
    container_name: test_runner
    volumes:
      - ./target/allure-results:/app/target/allure-results
    depends_on:
      redpanda:
        condition: service_healthy

  redpanda:
    image: docker.io/redpandadata/redpanda:v23.3.6
    container_name: test_redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 3s
      timeout: 3s
      retries: 5
